### ISSUE TITLE
ankerctl config import broken

### ISSUE THREAD

**Issue by spuder** [Ankermgmt/ankermake-m5-protocol#25]
Seeing this error when running an ankerctl config import (on the chrivers/pppp-improvements branch commit: 0339ef71782e6e8e4bdafd507659cfa7ad365b68)

```
./ankerctl.py config import
[*] Loading cache..
[*] Initializing API..
[*] Requesting profile data..
Traceback (most recent call last):
  File "/Users/spuder/Code/github/Ankermgmt/ankermake-m5-protocol/./ankerctl.py", line 369, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spuder/Code/github/Ankermgmt/ankermake-m5-protocol/./ankerctl.py", line 337, in config_import
    config = cli.config.load_config_from_api(auth_token, region, env.insecure)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spuder/Code/github/Ankermgmt/ankermake-m5-protocol/cli/config.py", line 91, in load_config_from_api
    profile = ppapi.profile()
              ^^^^^^^^^^^^^^^
  File "/Users/spuder/Code/github/Ankermgmt/ankermake-m5-protocol/libflagship/httpapi.py", line 13, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spuder/Code/github/Ankermgmt/ankermake-m5-protocol/libflagship/httpapi.py", line 90, in profile
    return self._get("/profile", headers={"X-Auth-Token": self._auth})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spuder/Code/github/Ankermgmt/ankermake-m5-protocol/libflagship/httpapi.py", line 33, in wrapper
    raise ValueError(f"API request failed: {data.status_code} {data.reason}")
ValueError: API request failed: 401 Unauthorized
```

## Theories

I haven't opened the anker slicer in a couple of days/weeks. Maybe my credentials expired?

**Comment by spuder** [comment]
Opening the slicer shows this error, which seems to indicate that ankerctl can't handle when reauthentication is required

<img width="1546" alt="Screen Shot 2023-04-02 at 10 46 38 PM" src="https://user-images.githubusercontent.com/242382/229413958-760e2b44-d143-4579-b227-79d6a04b6924.png">

**Comment by chrivers** [comment]
Yes, indeed.

Another issue is having to enter a CAPTCHA if you try to login too many times in a row (*even if successful*), which is also very hard to handle in a CLI tool.

I'll add some exception handling to this at some point, to give it a better presentation.
