### ISSUE TITLE
Docker crashing on run

### ISSUE THREAD

**Issue by yourjelly** [Ankermgmt/ankermake-m5-protocol#39]
Traceback (most recent call last):
  File "/app/ankerctl.py", line 516, in <module>
    main()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ankerctl.py", line 81, in main
    env.upgrade_config_if_needed()
  File "/app/ankerctl.py", line 40, in upgrade_config_if_needed
    with self.config.open():
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/app/cli/config.py", line 29, in _borrow
    pr = self.load(value, default)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/cli/config.py", line 65, in load
    return json.load(path.open(), object_hook=self._load_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid control character at: line 18 column 121 (char 584)

**Comment by yourjelly** [comment]
Okay, so the mistake I did here was assume that I could take the config decode from one computer copy it into a default.json on another computer and run that. But the information shown in the decode is different than what populates the default.json

**Comment by chrivers** [comment]
Thanks for trying out ankerctl!

I'm glad you worked out the problem. Let us know if you have any other issues :)
